Allow custom params to ykfde-open
agherzan/yubikey-full-disk-encryption pull request #64
Opened 2020-08-30 16:48 UTC by cyrinux

Hi,

Thanks for this project,

I'm trying to use luks detached header, and so come this little patch.

This add the support for ykfde-open. This is already good for ykfde-format.

* To be able to use a detached header:

```
ykfde-open -d /dev/sda2 -n luks -- --header /dev/sdb1
```

We can also pass more luks parameters if needed.

Regards

2020-09-02 19:51 UTC, Vincent43 requested changes
Thx for this contribution. Beside few inline nitpicks I would like if you can add info about this feature in [Readme](https://github.com/agherzan/yubikey-full-disk-encryption#unlock-luks-encrypted-volume-protected-by-ykfde-passphrase).

2020-09-02 19:51 UTC, Vincent43 commented on src/ykfde-open
> +shift $((OPTIND -1))
I think we can double quote this for safety like `shift "$((OPTIND -1))"`

2020-09-02 19:51 UTC, Vincent43 commented on src/ykfde-open
> +  [ "$DBG" ] && printf '%s\n' " > Decrypting with 'cryptsetup luksOpen $YKFDE_LUKS_DEV $YKFDE_LUKS_NAME $YKFDE_LUKS_OPTIONS $YKFDE_LUKS_KEYSLOT $@'..." || echo " > Decrypting with 'cryptsetup'..."
Please fix following warning from shellcheck by changing `$@` to `$*`:

```
In ykfde-open line 170:
  [ "$DBG" ] && printf '%s\n' " > Decrypting with 'cryptsetup luksOpen $YKFDE_TEST_PASSPHRASE $YKFDE_LUKS_DEV $YKFDE_LUKS_KEYSLOT $@'..." || echo " > Decrypting with 'cryptsetup'..."
                                                                                                                                  ^-- SC2145: Argument mixes string and array. Use * or separate argument.
```

2020-09-02 19:51 UTC, Vincent43 commented on src/ykfde-open
> +  [ "$DBG" ] && printf '%s\n' " > Decrypting with 'cryptsetup luksOpen $YKFDE_TEST_PASSPHRASE $YKFDE_LUKS_DEV $YKFDE_LUKS_KEYSLOT $@'..." || echo " > Decrypting with 'cryptsetup'..."
Please fix following warning from shellcheck by changing `$@` to `$*`:

```
In ykfde-open line 162:
  [ "$DBG" ] && printf '%s\n' " > Decrypting with 'cryptsetup luksOpen $YKFDE_TEST_PASSPHRASE $YKFDE_LUKS_DEV $YKFDE_LUKS_KEYSLOT $@'..." || echo " > Decrypting with 'cryptsetup'..."
                                                                                                                                  ^-- SC2145: Argument mixes string and array. Use * or separate argument.
```

2020-09-03 08:00 UTC, cyrinux commented
Hi,
I can't test try right now, but should be ok. :)

2020-09-03 11:35 UTC, Vincent43 approved these changes
Ok, thx. If you find some more time you may enhance ykfde-enroll script in the same way.

2020-09-03 11:37 UTC, merged